version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - php-fpm
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d

  php-fpm:
    build:
      context: ./php
    volumes:
      - ./src:/var/www
    depends_on:
      - db

  db:
    image: postgres:13
    ports:
      - '5434:5432'
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
